### ISSUE TITLE
Future Outcome Date in Retention Dataset

### ISSUE THREAD

**Issue by orrinft** [mozaude/MozART_Analytical#12]
Fixing the outcome of patients that have their next appoint/drug pickup in the future.

Timoteo suggested this code:

CTE1 AS
( 
       SELECT *, 
       CASE WHEN ((cast(datainiciotarv AS DATE) <Outcome_Date) AND ((datasaidatarv < Max_datatarv) OR (datasaidatarv IS NULL) OR (datasaidatarv < Max_dataseguimento) OR (datasaidatarv > Outcome_Date))) AND 
       ((Max_datatarv > dateadd(dd,-90,Outcome_Date) AND Max_datatarv <= Outcome_Date) OR (dataproxima > dateadd(dd,-60,Outcome_Date) AND dataproxima <= Outcome_Date) OR (Max_dataseguimento > dateadd(dd, -90, Outcome_Date) AND Max_dataseguimento <= Outcome_Date)) THEN 'Retained'
       WHEN Outcome_Date>cast(CURRENT_TIMESTAMP as date) THEN NULL
       Else 'Not Retained'
       END AS [Retained_Status]
       FROM CTE0
),
CTE2 AS
( 
       SELECT *, CASE WHEN Retained_Status = 'Not Retained' AND ((codestado = 'ABANDONO') OR (codestado IS NULL) AND (datasaidatarv < Outcome_Date)) THEN 'LTFU'
       WHEN Retained_Status = 'Not Retained' AND ((codestado = 'TRANSFERIDO PARA') AND (datasaidatarv < Outcome_Date)) THEN 'Transferred Out'
       WHEN Retained_Status = 'Not Retained' AND ((codestado = 'OBITOU') AND (datasaidatarv < Outcome_Date)) THEN 'Dead'
       WHEN Retained_Status = 'Not Retained' AND ((codestado IS NULL)) THEN 'LTFU'
       WHEN Retained_Status = 'Retained' Then 'Retained'
       ELSE 'LTFU'
       END AS [Outcome]
       FROM CTE1
       WHERE Retained_Status IS NOT NULL)

**Comment by randyyee** [comment]
Code changed with a new status, "Not Evaluated," for those with outcome dates beyond the current date
